apiVersion: v1
kind: Service
metadata:
  name: ms-orizon-api-service
  labels:
    app: ms-orizon-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ms-orizon-api
